/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApkRouteImport } from './routes/apk'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CitatsRouteImport } from './routes/citats'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GameRouteImport } from './routes/game'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ZashkvaryRouteImport } from './routes/zashkvary'
import { Route as ApiOfflineRouteImport } from './routes/api/offline'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as CharactersMapRouteImport } from './routes/characters.map'
import { Route as GameIndexRouteImport } from './routes/game.index'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as GameArkRouteImport } from './routes/game.ark'
import { Route as GameAvRouteImport } from './routes/game.av'
import { Route as GameCrosswordsRouteImport } from './routes/game.crosswords'
import { Route as GameQuestRouteImport } from './routes/game.quest'
import { Route as GameSvoyaRouteImport } from './routes/game.svoya'
import { Route as PressIdRouteImport } from './routes/press.$id'
import { Route as StorySlugRouteImport } from './routes/story.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosCatRouteImport } from './routes/videos.$cat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApkRoute = ApkRouteImport.update({
  id: '/apk',
  path: '/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CitatsRoute = CitatsRouteImport.update({
  id: '/citats',
  path: '/citats',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ZashkvaryRoute = ZashkvaryRouteImport.update({
  id: '/zashkvary',
  path: '/zashkvary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfflineRoute = ApiOfflineRouteImport.update({
  id: '/api/offline',
  path: '/api/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersMapRoute = CharactersMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CharactersRoute,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameRoute,
} as any)
const GameArkRoute = GameArkRouteImport.update({
  id: '/ark',
  path: '/ark',
  getParentRoute: () => GameRoute,
} as any)
const GameAvRoute = GameAvRouteImport.update({
  id: '/av',
  path: '/av',
  getParentRoute: () => GameRoute,
} as any)
const GameCrosswordsRoute = GameCrosswordsRouteImport.update({
  id: '/crosswords',
  path: '/crosswords',
  getParentRoute: () => GameRoute,
} as any)
const GameQuestRoute = GameQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => GameRoute,
} as any)
const GameSvoyaRoute = GameSvoyaRouteImport.update({
  id: '/svoya',
  path: '/svoya',
  getParentRoute: () => GameRoute,
} as any)
const PressIdRoute = PressIdRouteImport.update({
  id: '/press/$id',
  path: '/press/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySlugRoute = StorySlugRouteImport.update({
  id: '/story/$slug',
  path: '/story/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const VideosCatRoute = VideosCatRouteImport.update({
  id: '/$cat',
  path: '/$cat',
  getParentRoute: () => VideosRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/changelog': typeof ChangelogRoute
  '/channel': typeof ChannelRoute
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRoute
  '/citats': typeof CitatsRoute
  '/donate': typeof DonateRoute
  '/game': typeof GameRouteWithChildren
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/passport': typeof PassportRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRouteWithChildren
  '/zashkvary': typeof ZashkvaryRoute
  '/api/offline': typeof ApiOfflineRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/map': typeof CharactersMapRoute
  '/game/$id': typeof GameIdRoute
  '/game/ark': typeof GameArkRoute
  '/game/av': typeof GameAvRoute
  '/game/crosswords': typeof GameCrosswordsRoute
  '/game/quest': typeof GameQuestRoute
  '/game/svoya': typeof GameSvoyaRoute
  '/press/$id': typeof PressIdRoute
  '/story/$slug': typeof StorySlugRoute
  '/videos/$cat': typeof VideosCatRoute
  '/characters/': typeof CharactersIndexRoute
  '/game/': typeof GameIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/changelog': typeof ChangelogRoute
  '/channel': typeof ChannelRoute
  '/chat': typeof ChatRoute
  '/citats': typeof CitatsRoute
  '/donate': typeof DonateRoute
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/passport': typeof PassportRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/zashkvary': typeof ZashkvaryRoute
  '/api/offline': typeof ApiOfflineRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/map': typeof CharactersMapRoute
  '/game/$id': typeof GameIdRoute
  '/game/ark': typeof GameArkRoute
  '/game/av': typeof GameAvRoute
  '/game/crosswords': typeof GameCrosswordsRoute
  '/game/quest': typeof GameQuestRoute
  '/game/svoya': typeof GameSvoyaRoute
  '/press/$id': typeof PressIdRoute
  '/story/$slug': typeof StorySlugRoute
  '/videos/$cat': typeof VideosCatRoute
  '/characters': typeof CharactersIndexRoute
  '/game': typeof GameIndexRoute
  '/videos': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apk': typeof ApkRoute
  '/changelog': typeof ChangelogRoute
  '/channel': typeof ChannelRoute
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRoute
  '/citats': typeof CitatsRoute
  '/donate': typeof DonateRoute
  '/game': typeof GameRouteWithChildren
  '/ideas': typeof IdeasRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/passport': typeof PassportRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/videos': typeof VideosRouteWithChildren
  '/zashkvary': typeof ZashkvaryRoute
  '/api/offline': typeof ApiOfflineRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/map': typeof CharactersMapRoute
  '/game/$id': typeof GameIdRoute
  '/game/ark': typeof GameArkRoute
  '/game/av': typeof GameAvRoute
  '/game/crosswords': typeof GameCrosswordsRoute
  '/game/quest': typeof GameQuestRoute
  '/game/svoya': typeof GameSvoyaRoute
  '/press/$id': typeof PressIdRoute
  '/story/$slug': typeof StorySlugRoute
  '/videos/$cat': typeof VideosCatRoute
  '/characters/': typeof CharactersIndexRoute
  '/game/': typeof GameIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apk'
    | '/changelog'
    | '/channel'
    | '/characters'
    | '/chat'
    | '/citats'
    | '/donate'
    | '/game'
    | '/ideas'
    | '/login'
    | '/offline'
    | '/passport'
    | '/saved'
    | '/settings'
    | '/videos'
    | '/zashkvary'
    | '/api/offline'
    | '/characters/$id'
    | '/characters/map'
    | '/game/$id'
    | '/game/ark'
    | '/game/av'
    | '/game/crosswords'
    | '/game/quest'
    | '/game/svoya'
    | '/press/$id'
    | '/story/$slug'
    | '/videos/$cat'
    | '/characters/'
    | '/game/'
    | '/videos/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apk'
    | '/changelog'
    | '/channel'
    | '/chat'
    | '/citats'
    | '/donate'
    | '/ideas'
    | '/login'
    | '/offline'
    | '/passport'
    | '/saved'
    | '/settings'
    | '/zashkvary'
    | '/api/offline'
    | '/characters/$id'
    | '/characters/map'
    | '/game/$id'
    | '/game/ark'
    | '/game/av'
    | '/game/crosswords'
    | '/game/quest'
    | '/game/svoya'
    | '/press/$id'
    | '/story/$slug'
    | '/videos/$cat'
    | '/characters'
    | '/game'
    | '/videos'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apk'
    | '/changelog'
    | '/channel'
    | '/characters'
    | '/chat'
    | '/citats'
    | '/donate'
    | '/game'
    | '/ideas'
    | '/login'
    | '/offline'
    | '/passport'
    | '/saved'
    | '/settings'
    | '/videos'
    | '/zashkvary'
    | '/api/offline'
    | '/characters/$id'
    | '/characters/map'
    | '/game/$id'
    | '/game/ark'
    | '/game/av'
    | '/game/crosswords'
    | '/game/quest'
    | '/game/svoya'
    | '/press/$id'
    | '/story/$slug'
    | '/videos/$cat'
    | '/characters/'
    | '/game/'
    | '/videos/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApkRoute: typeof ApkRoute
  ChangelogRoute: typeof ChangelogRoute
  ChannelRoute: typeof ChannelRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  ChatRoute: typeof ChatRoute
  CitatsRoute: typeof CitatsRoute
  DonateRoute: typeof DonateRoute
  GameRoute: typeof GameRouteWithChildren
  IdeasRoute: typeof IdeasRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  PassportRoute: typeof PassportRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  VideosRoute: typeof VideosRouteWithChildren
  ZashkvaryRoute: typeof ZashkvaryRoute
  ApiOfflineRoute: typeof ApiOfflineRoute
  PressIdRoute: typeof PressIdRoute
  StorySlugRoute: typeof StorySlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apk': {
      id: '/apk'
      path: '/apk'
      fullPath: '/apk'
      preLoaderRoute: typeof ApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citats': {
      id: '/citats'
      path: '/citats'
      fullPath: '/citats'
      preLoaderRoute: typeof CitatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zashkvary': {
      id: '/zashkvary'
      path: '/zashkvary'
      fullPath: '/zashkvary'
      preLoaderRoute: typeof ZashkvaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offline': {
      id: '/api/offline'
      path: '/api/offline'
      fullPath: '/api/offline'
      preLoaderRoute: typeof ApiOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/map': {
      id: '/characters/map'
      path: '/map'
      fullPath: '/characters/map'
      preLoaderRoute: typeof CharactersMapRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/ark': {
      id: '/game/ark'
      path: '/ark'
      fullPath: '/game/ark'
      preLoaderRoute: typeof GameArkRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/av': {
      id: '/game/av'
      path: '/av'
      fullPath: '/game/av'
      preLoaderRoute: typeof GameAvRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/crosswords': {
      id: '/game/crosswords'
      path: '/crosswords'
      fullPath: '/game/crosswords'
      preLoaderRoute: typeof GameCrosswordsRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/quest': {
      id: '/game/quest'
      path: '/quest'
      fullPath: '/game/quest'
      preLoaderRoute: typeof GameQuestRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/svoya': {
      id: '/game/svoya'
      path: '/svoya'
      fullPath: '/game/svoya'
      preLoaderRoute: typeof GameSvoyaRouteImport
      parentRoute: typeof GameRoute
    }
    '/press/$id': {
      id: '/press/$id'
      path: '/press/$id'
      fullPath: '/press/$id'
      preLoaderRoute: typeof PressIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$slug': {
      id: '/story/$slug'
      path: '/story/$slug'
      fullPath: '/story/$slug'
      preLoaderRoute: typeof StorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/$cat': {
      id: '/videos/$cat'
      path: '/$cat'
      fullPath: '/videos/$cat'
      preLoaderRoute: typeof VideosCatRouteImport
      parentRoute: typeof VideosRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CharactersRouteChildren {
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersMapRoute: typeof CharactersMapRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersIdRoute: CharactersIdRoute,
  CharactersMapRoute: CharactersMapRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface GameRouteChildren {
  GameIdRoute: typeof GameIdRoute
  GameArkRoute: typeof GameArkRoute
  GameAvRoute: typeof GameAvRoute
  GameCrosswordsRoute: typeof GameCrosswordsRoute
  GameQuestRoute: typeof GameQuestRoute
  GameSvoyaRoute: typeof GameSvoyaRoute
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameIdRoute: GameIdRoute,
  GameArkRoute: GameArkRoute,
  GameAvRoute: GameAvRoute,
  GameCrosswordsRoute: GameCrosswordsRoute,
  GameQuestRoute: GameQuestRoute,
  GameSvoyaRoute: GameSvoyaRoute,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

interface VideosRouteChildren {
  VideosCatRoute: typeof VideosCatRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosCatRoute: VideosCatRoute,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApkRoute: ApkRoute,
  ChangelogRoute: ChangelogRoute,
  ChannelRoute: ChannelRoute,
  CharactersRoute: CharactersRouteWithChildren,
  ChatRoute: ChatRoute,
  CitatsRoute: CitatsRoute,
  DonateRoute: DonateRoute,
  GameRoute: GameRouteWithChildren,
  IdeasRoute: IdeasRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  PassportRoute: PassportRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  VideosRoute: VideosRouteWithChildren,
  ZashkvaryRoute: ZashkvaryRoute,
  ApiOfflineRoute: ApiOfflineRoute,
  PressIdRoute: PressIdRoute,
  StorySlugRoute: StorySlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
